language: objective-c

script: xcodebuild -project ConApp.xcodeproj -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO 

after_success:
    "zip -r ReferenceConApp.zip /Users/travis/build/rytina/iOS-DukeConApp/build/Release-iphonesimulator/ConApp.app && curl -T ReferenceConApp.zip -u $FTP_USER:$FTP_PASS ftp.hosting-agency.de/public_html/dukecon-apps/"
