language: objective-c

script: xcodebuild -project ConApp.xcodeproj -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO 

addons:
  artifacts: true

addons:
  artifacts:
	paths:
    	- /Users/travis/build/rytina/iOS-DukeConApp/build/Release-iphonesimulator/ConApp.app
        - $(git ls-files -o | tr "\n" ":")
